# Generated by Django 4.2.6 on 2023-10-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
